### ISSUE TITLE
Error "get_distance vars not an array" on castles

### ISSUE THREAD

**Issue by dmunozc** [dmunozc/bc19-g8#15]
When running the following map seed 1183275701
Castles throw error "get_distance vars not an array"
Really cryptic. Was able to narrow it down to this function:

resource_clusters = resource.find_clusters(resource_list, friendly_castles, enemy_castles);

When you comment that one out the problem goes away

Please investigate

**Comment by jlewisbrewer** [comment]
alright

**Comment by jlewisbrewer** [comment]
The issue is the castles don't have enough fuel to signal far enough so they can create the friendly castle array. I'll have to rethink the initialization
